// <auto-generated />
namespace KidKinderYeni.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig13));
        
        string IMigrationMetadata.Id
        {
            get { return "202405022026215_mig13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
